services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    container_name: frontend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --url http://frontend:3001
    depends_on:
      - frontend
    restart: unless-stopped
